apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: server-storage-io1
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
